---
.travis.yml:
  secure: "m2yA2rrOr9n7/i+MKy79AF7P/dLwT+eyEz8VtKDZRfRW12kkRF80d3KD+cYLI4KRZmypsF1COHCkKwwBPXeOpfYcSsgvRqUubkHbRxdB91ZkU4uLgWhASr3pd6qV7Yede8NlFwMSf7Y4RAqH4ui1kKTI/IYFVjP13ok2LFODLag="
spec/spec_helper.rb:
  mock_with: ':mocha'
